export const products = [
  {
    coverImage: './assets/img/phone-cover.jpg',
    name: 'Phone XL',
    price: 799,
    description: 'A large phone with one of the best screens',
    heading1: 'サンプルテキスト１',
    heading2: 'サンプルテキスト２',
    heading3: 'サンプルテキスト３',
    headingtext1: 'サンプルテキスト サンプルテキスト サンプルテキスト サンプルテキスト',
    headingtext2: 'サンプルテキスト サンプルテキスト',
    headingtext3: 'サンプルテキスト サンプルテキスト サンプルテキスト サンプルテキスト サンプルテキスト',
  },
  {
    coverImage: './assets/img/phone-cover.jpg',
    name: 'Phone Mini',
    price: 699,
    description: 'A great phone with one of the best cameras',
    heading1: 'サンプルテキスト１',
    heading2: 'サンプルテキスト２',
    heading3: 'サンプルテキスト３',
    headingtext1: 'サンプルテキスト サンプルテキスト サンプルテキスト サンプルテキスト',
    headingtext2: 'サンプルテキスト サンプルテキスト',
    headingtext3: 'サンプルテキスト サンプルテキスト サンプルテキスト サンプルテキスト サンプルテキスト',
  },
  {
    coverImage: './assets/img/phone-cover.jpg',
    name: 'Phone Standard',
    price: 299,
    description: '',
    heading1: 'サンプルテキスト１',
    heading2: 'サンプルテキスト２',
    heading3: 'サンプルテキスト３',
    headingtext1: 'サンプルテキスト サンプルテキスト サンプルテキスト サンプルテキスト',
    headingtext2: 'サンプルテキスト サンプルテキスト',
    headingtext3: 'サンプルテキスト サンプルテキスト サンプルテキスト サンプルテキスト サンプルテキスト',
  },
  {
    coverImage: './assets/img/phone-cover.jpg',
    name: 'Phone Special',
    price: 599,
    description: '',
    heading1: 'サンプルテキスト１',
    heading2: 'サンプルテキスト２',
    heading3: 'サンプルテキスト３',
    headingtext1: 'サンプルテキスト サンプルテキスト サンプルテキスト サンプルテキスト',
    headingtext2: 'サンプルテキスト サンプルテキスト',
    headingtext3: 'サンプルテキスト サンプルテキスト サンプルテキスト サンプルテキスト サンプルテキスト',
  }

];
